2025-09-04 01:02:53,360: [11] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2025-09-04 01:02:53,360: [11] m.main:INFO: Beginning analysis
2025-09-04 01:02:53,362: [11] m.e.manticore:INFO: Starting symbolic create contract
2025-09-04 01:02:53,862: [11] m.e.manticore:INFO: Starting symbolic transaction: 0
2025-09-04 01:02:55,224: [11] m.e.manticore:INFO: Found a concrete globalsha3 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' -> 73138091548938366139099779971772605061518111956507126412222883840269740007539
2025-09-04 01:02:56,309: [11] m.c.worker:ERROR: Exception in state 5: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2025-09-04 01:02:57,034: [11] m.e.manticore:INFO: 2 alive states, 1 terminated states
2025-09-04 01:02:57,218: [11] m.e.manticore:INFO: Starting symbolic transaction: 1
2025-09-04 01:03:01,975: [11] m.c.worker:ERROR: Exception in state 3: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2025-09-04 01:03:02,012: [11] m.c.worker:ERROR: Exception in state 11: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2025-09-04 01:03:04,452: [11] m.e.manticore:INFO: 4 alive states, 1 terminated states
2025-09-04 01:03:04,684: [98] m.c.manticore:INFO: Generated testcase No. 0 - STOP(3 txs)
2025-09-04 01:03:04,685: [98] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2025-09-04 01:03:04,703: [99] m.c.manticore:INFO: Generated testcase No. 1 - STOP(3 txs)
2025-09-04 01:03:04,703: [99] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2025-09-04 01:03:04,714: [100] m.c.manticore:INFO: Generated testcase No. 2 - STOP(3 txs)
2025-09-04 01:03:04,715: [100] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2025-09-04 01:03:04,724: [102] m.c.manticore:INFO: Generated testcase No. 3 - STOP(3 txs)
2025-09-04 01:03:04,725: [102] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2025-09-04 01:03:05,944: [11] m.c.manticore:INFO: Results in /mcore_4mw9sluv
2025-09-04 01:03:05,944: [11] m.c.manticore:INFO: Total time: 8.705894708633423
