2025-09-03 22:53:49,387: [11] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2025-09-03 22:53:49,388: [11] m.main:INFO: Beginning analysis
2025-09-03 22:53:49,390: [11] m.e.manticore:INFO: Starting symbolic create contract
2025-09-03 22:53:49,876: [11] m.e.manticore:INFO: Starting symbolic transaction: 0
2025-09-03 22:53:51,224: [11] m.e.manticore:INFO: Found a concrete globalsha3 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' -> 73138091548938366139099779971772605061518111956507126412222883840269740007539
2025-09-03 22:53:52,318: [11] m.c.worker:ERROR: Exception in state 7: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2025-09-03 22:53:52,975: [11] m.e.manticore:INFO: 2 alive states, 1 terminated states
2025-09-03 22:53:53,152: [11] m.e.manticore:INFO: Starting symbolic transaction: 1
2025-09-03 22:53:57,460: [11] m.c.worker:ERROR: Exception in state 3: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2025-09-03 22:53:59,151: [11] m.c.worker:ERROR: Exception in state 5: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2025-09-03 22:54:00,355: [11] m.e.manticore:INFO: 4 alive states, 1 terminated states
2025-09-03 22:54:00,640: [89] m.c.manticore:INFO: Generated testcase No. 0 - STOP(3 txs)
2025-09-03 22:54:00,641: [89] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2025-09-03 22:54:00,652: [90] m.c.manticore:INFO: Generated testcase No. 1 - STOP(3 txs)
2025-09-03 22:54:00,653: [90] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2025-09-03 22:54:00,655: [91] m.c.manticore:INFO: Generated testcase No. 2 - STOP(3 txs)
2025-09-03 22:54:00,656: [91] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2025-09-03 22:54:00,667: [93] m.c.manticore:INFO: Generated testcase No. 3 - STOP(3 txs)
2025-09-03 22:54:00,668: [93] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2025-09-03 22:54:01,852: [11] m.c.manticore:INFO: Results in /mcore_iqlkfxcb
2025-09-03 22:54:01,852: [11] m.c.manticore:INFO: Total time: 8.681355953216553
