2025-06-28 23:58:15,196: [11] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2025-06-28 23:58:15,197: [11] m.main:INFO: Beginning analysis
2025-06-28 23:58:15,199: [11] m.e.manticore:INFO: Starting symbolic create contract
2025-06-28 23:58:15,944: [11] m.e.manticore:INFO: Starting symbolic transaction: 0
2025-06-28 23:58:22,738: [11] m.c.worker:ERROR: Exception in state 10: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2025-06-28 23:58:22,816: [11] m.e.manticore:INFO: Found a concrete globalsha3 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01' -> 80084422859880547211683076133703299733277748156566366325829078699459944778998
2025-06-28 23:58:27,292: [11] m.e.manticore:INFO: 1 alive states, 3 terminated states
2025-06-28 23:58:27,595: [11] m.e.manticore:INFO: Starting symbolic transaction: 1
2025-06-28 23:58:33,956: [11] m.c.worker:ERROR: Exception in state 11: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2025-06-28 23:58:38,926: [11] m.e.manticore:INFO: 1 alive states, 5 terminated states
2025-06-28 23:58:39,304: [90] m.c.manticore:INFO: Generated testcase No. 0 - STOP(3 txs)
2025-06-28 23:58:39,305: [90] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2025-06-28 23:58:41,062: [11] m.c.manticore:INFO: Results in /mcore_g8mecipi
2025-06-28 23:58:41,062: [11] m.c.manticore:INFO: Total time: 13.4588041305542
