2025-09-03 23:43:24,260: [11] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2025-09-03 23:43:24,261: [11] m.main:INFO: Beginning analysis
2025-09-03 23:43:24,262: [11] m.e.manticore:INFO: Starting symbolic create contract
2025-09-03 23:43:24,765: [11] m.e.manticore:INFO: Starting symbolic transaction: 0
2025-09-03 23:43:26,132: [11] m.e.manticore:INFO: Found a concrete globalsha3 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' -> 73138091548938366139099779971772605061518111956507126412222883840269740007539
2025-09-03 23:43:27,284: [11] m.c.worker:ERROR: Exception in state 8: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2025-09-03 23:43:28,003: [11] m.e.manticore:INFO: 2 alive states, 1 terminated states
2025-09-03 23:43:28,190: [11] m.e.manticore:INFO: Starting symbolic transaction: 1
2025-09-03 23:43:32,319: [11] m.c.worker:ERROR: Exception in state 3: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2025-09-03 23:43:32,702: [11] m.c.worker:ERROR: Exception in state 4: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2025-09-03 23:43:35,201: [11] m.e.manticore:INFO: 4 alive states, 1 terminated states
2025-09-03 23:43:35,440: [92] m.c.manticore:INFO: Generated testcase No. 0 - STOP(3 txs)
2025-09-03 23:43:35,441: [92] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2025-09-03 23:43:35,463: [94] m.c.manticore:INFO: Generated testcase No. 1 - STOP(3 txs)
2025-09-03 23:43:35,464: [93] m.c.manticore:INFO: Generated testcase No. 2 - STOP(3 txs)
2025-09-03 23:43:35,464: [94] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2025-09-03 23:43:35,465: [93] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2025-09-03 23:43:35,481: [96] m.c.manticore:INFO: Generated testcase No. 3 - STOP(3 txs)
2025-09-03 23:43:35,481: [96] m.c.plugin:WARNING: Caught will_solve in state None, but failed to capture its initialization
2025-09-03 23:43:36,702: [11] m.c.manticore:INFO: Results in /mcore_rk6f1gzd
2025-09-03 23:43:36,702: [11] m.c.manticore:INFO: Total time: 8.492603302001953
